- name: "Practicing the Ansible play books"
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: "username:"
      private: no
    - name: password
      prompt: "password:"
      private: yes
  tasks:
  - name: Pring the course deatils
    ansible.builtin.debug:
      msg: "My username is {{ username }} and password is {{ password }}"