- name: "Practicing the Ansible play books"
  hosts: frontend
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: Start and Enable the nginx
    ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes