- name: "Practicing the Ansible play books"
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: printing the names
    ansible.builtin.package:
      msg: "{{ item }}"
      state: latest
    loop:
    - nginx
    - nodejs
    - mysql
    - zip
