- name: "Practicing the Ansible play books"
  hosts: localhost
  become: yes
  tasks:
  - name: printing the names
    ansible.builtin.package:
      msg: "{{ item }}"
      state: present
    loop:
    - nginx
    - nodejs
    - mysql
    - zip
